#!/bin/bash

#####################################
# Rev:           v0.60              #
# Last mofified: 2021/06/09         #
#####################################

##### Run/process control variables #####
# Whether or not to create processed scripts
export PROC_DC="1"
export PROC_IV="1"

# Whether or not to run DC and/or IV with processed scripts
export RUN_DC="1"
export RUN_IV="1"

# Whether or not to quit DC and/or IV after tcl scripts finish
export DC_QUIT="1"
export IV_QUIT="1"

# Whether or not to ***REMOVE*** the "generated" folder ***AND*** run cleanup.sh in the working directory
export CLEAN_GEN="0"


##### Design Compiler #####
# Set to 1 to save a number of reports from Design Compiler
export DC_SAVE_REPS="1"
# Names of clk nets. Leave empty for logic-based designs
# e.g. "clk" or "CLK"
export DC_CLK_NETS=""
# Clock frequency in MHz
export DC_CLK_FREQ="100"
# Rise time: 100ps
export DC_TRISE="0.1"
# Fall time: 100ps
export DC_TFALL="0.1"

# Number of stages for clock gating
export DC_CG_STAGES="2"
# Minimum bitwidth for clock gating
export DC_CG_BITWIDTH="4"


##### Innovus #####
# Whether or not to load Calibre RealTime
export IV_USE_MGCRT="1"

export IV_NUM_THREADS="32"

# Whether or not to open the Innovus GUI
export IV_USE_GUI="0"

# Set to "1" to try using OA libraries instead of LEF files [EXPERIMENTAL]
export IV_USE_OA="0"

### Design settings ###
# Aspect Ratio
export IV_DES_ASPECT="0.8"
export IV_DES_DENSITY="0.7"
# Margin around design for rings, etc.
# MAKE SURE THIS is > ((# pwr nets + # gnd nets) x IV_*_RING_WIDTH + IV_*_RING_SPACE + IV_*_RING_OFFSET)
export IV_DES_MARGIN_LEFT="10"
export IV_DES_MARGIN_BOT="10"
export IV_DES_MARGIN_RIGHT="10"
export IV_DES_MARGIN_TOP="10"

# All power/ground nets
export IV_PWR_NETS="vdd!"
export IV_GND_NETS="gnd!"
# Core power/ground nets
export IV_PWR_CORE="vdd!"
export IV_GND_CORE="gnd!"


### Power rings ###
# Which layers should be used for horizontal and vertical parts of ring
export IV_HORZ_RING_LAYER="BA"
export IV_VERT_RING_LAYER="BB"
# Which layer range is allowed for vias connections
export IV_RING_BOT_VIA_LAYER="M1"
export IV_RING_TOP_VIA_LAYER="BB"

export IV_HORZ_RING_WIDTH="2"
export IV_VERT_RING_WIDTH="2"
export IV_HORZ_RING_SPACE="2"
export IV_VERT_RING_SPACE="2"
export IV_HORZ_RING_OFFSET="2"
export IV_VERT_RING_OFFSET="2"

### Power Stripes ###
# Which layers should be used for stripes
export IV_STRIPE_LAYER="BB"
# Which layer range is allowed for vias connections
export IV_STRIPE_BOT_VIA_LAYER="M1"
export IV_STRIPE_TOP_VIA_LAYER="BB"
# Power stripe starting offset, set-to-set distance, width, and spacing
export IV_STRIPE_OFFSET="242"
export IV_STRIPE_DIST="242"
export IV_STRIPE_WIDTH="5"
export IV_STRIPE_SPACE="5"

# Which layer range nanoroute should use
export IV_TOP_NR_LAYER="5"
export IV_BOT_NR_LAYER="1"

### Settings for CTS ###
# Whether or not to skip CTS in Innovus script
export IV_SKIP_CTS="0"

# If set to 1, the "override_minimum_max_trans_target" property will
# be set to avoid IMPCCOPT-1013
export OVERRIDE_CTS_MAX_TRAN_TIME="0"

# Max transition time
# export IV_CTS_MAX_TRAN_TIME="0.1ns"
# export IV_CTS_MAX_TRAN_TIME="1ns"
export IV_CTS_MAX_TRAN_TIME="2ns"
# Skew target
# export IV_CTS_SKEW_TARGET="0.03ns"
export IV_CTS_SKEW_TARGET="0.5ns"
